//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiQScoreboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoreboardresults
    {
        public int id { get; set; }
        public string office { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> q1 { get; set; }
        public Nullable<decimal> q2 { get; set; }
        public Nullable<decimal> q3 { get; set; }
        public Nullable<decimal> q4 { get; set; }
        public Nullable<decimal> q5 { get; set; }
    }
}
